### ISSUE TITLE
Use unicode block

### ISSUE THREAD

**Issue by joshtriplett** [nabijaczleweli/termimage#4]
You can double the vertical resolution by printing a Unicode "upper block" character, using the foreground for the upper pixel and the background for the lower pixel.  (This also requires an adjustment to the aspect ratio calculation.)

**Comment by nabijaczleweli** [comment]
Aspect ratio is (not) preserved by `image`, so I have little control over that, but the idea seems nice

**Comment by joshtriplett** [comment]
You can read out the size, and calculate the new size yourself, rather than using the aspect-ratio-preserving resize.

Terminal characters have a rectangular shape, with more height than width; when not using Unicode, you'd want to take that into account, and resize the image to have twice as much width as height compared to its natural aspect ratio.  For instance, you could take a 1600x1200 image and resize it to 80x30 rather than 80x60, which would make the image printed in the terminal look closer to correct.

However, when using a unicode half-block character, you'd want to resize the image preserving aspect ratio (1600x1200 -> 80x60) and then use two pixel rows per text row.

**Comment by nabijaczleweli** [comment]
Yeah, you're right.

**Comment by nabijaczleweli** [comment]
> Terminal characters have a rectangular shape

Which is inconsistent across any and all implementations :P

**Comment by joshtriplett** [comment]
@nabijaczleweli True, but it'll generally be closer to 2:1 than 1:1; terminal fonts are almost never square.  So, 2:1 should generally produce better results.

**Comment by nabijaczleweli** [comment]
I'm bad at numbers, misclosed :v

**Comment by nabijaczleweli** [comment]
![DOPE SHIT, BOIZ](https://cloud.githubusercontent.com/assets/6709544/18569701/9e4e356c-7ba4-11e6-85f0-d3bc566e0c54.png)

**Comment by nabijaczleweli** [comment]
@joshtriplett Can you verify with `-a truecolor`?

**Comment by joshtriplett** [comment]
Yeah, that works, and produces a much better aspect ratio as well.

The unicode block thing came readily to mind because I'd done a similar experiment as a test of the `ansi_term` module after adding truecolor support to it. My quick-and-dirty version didn't have any of the error handling or command-line handling that yours does, though.

Screenshots of the truecolor Unicode-block version:

![rust-logo](https://cloud.githubusercontent.com/assets/162737/18570254/3d3773de-7b5d-11e6-978a-3d476fc0ab56.png)
![tali](https://cloud.githubusercontent.com/assets/162737/18570258/411279ae-7b5d-11e6-87a4-fc1c8ef990b6.png)

Also, I'd suggest subtracting one from the target height, so that the subsequent prompt doesn't scroll the top of the image off the screen.

**Comment by nabijaczleweli** [comment]
That's unavoidable on Windooze, but I might be able to do something about it on Linux, open a separate issue, please?

**Comment by nabijaczleweli** [comment]
@joshtriplett Can you please make an SS of this image: 
![DS3 SS](https://cloud.githubusercontent.com/assets/6709544/18579388/ab330d38-7bf5-11e6-954a-f6e9d44ebc75.png)?
That way we'd have a consistent comparison base for multiple platforms
