### ISSUE TITLE
Usage example for more input arguments

### ISSUE THREAD

**Issue by pothos** [nabijaczleweli/termimage#6]
To allow more than one file and directories you can include this script:

```
#!/bin/bash
for i in `find $@` ; do termimage --size 150x33 $i ; done
```

I set the size to allow piping into a file.

**Comment by nabijaczleweli** [comment]
Is the solution in the referenced commit satisfactory?

**Comment by pothos** [comment]
Yes, also good. Somehow my intention was to have this with $@ because it supports both mentioning multiple files as well as directories.
