### ISSUE TITLE
Usage with ncurses-rs

### ISSUE THREAD

**Issue by phimuemue** [nabijaczleweli/termimage#9]
Can termimage be used in conjunction with ncurses-rs (see https://github.com/jeaye/ncurses-rs)?

I would imagine something like outputting the image data to a `Vec<Vec<(Color, Color)>>` that then can be used by ncurses.

**Comment by nabijaczleweli** [comment]
What's `Color`? I couldn't find it in the linked repo.

**Comment by phimuemue** [comment]
I just wrote `Color` as a placeholder for the color constants. It's actually `i16` (see https://github.com/jeaye/ncurses-rs/blob/8ac680c5549c998fc9c1c0051c6b0f98cd0fa397/src/constants.rs).

**Comment by nabijaczleweli** [comment]
Let's not do that explicitly but instead let's DRY out some code in such a way to make this simple!

**Comment by nabijaczleweli** [comment]
You can use [`ops::create_colourtable()`](https://github.com/nabijaczleweli/termimage/blob/e1be450f3074bce5425ace26e569616086d4af2c/src/ops/mod.rs#L128-L165) now and display the images yourself with `ncurses-rs` manually in a simple fashion, thanks for the suggestion.

**Comment by nabijaczleweli** [comment]
Released in [v0.3.0](https://github.com/nabijaczleweli/termimage/releases/tag/v0.3.0)

**Comment by nabijaczleweli** [comment]
That was a great suggestion, @phimuemue, thanks!
